### ISSUE TITLE
Obol does not support setting an existing group as the primary group for a new user

### ISSUE THREAD

**Issue by hicham-a** [clustervision/trinityX#219]
It would be nice to have an option to set the primary group of a new user instead of creating one
Something along the lines:

`# obol user add test -g admins`

**Comment by Marc69** [comment]
The basic functionality is there and it stood the standard tests, but I found some possible issues:

-  After deleting all my test users I got:
```
[root@controller1 controller]# obol user list
[root@controller1 controller]# obol group list
150 admins
151 users
1066 john
1067 jane
12345 joe
345 jim
12345 jerry
345 jack
```
Hitherto the (unique) primary group was deleted along with the user, but not any more. That may be unavoidable, but I think we should put in a warning that the group still exists.

- When trying to add a new user to a non-existent group, I got:
```
[root@controller1 controller]# obol user add --password 123 --group superusers june
gidNumber = False
Traceback (most recent call last):
  File "/usr/local/bin/obol", line 561, in <module>
    cmd(**args)
  File "/usr/local/bin/obol", line 144, in user_add
    conn.add_s(dn, add_record)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 195, in add_s
    return self.result(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 458, in result
    resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 462, in result2
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 469, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 476, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
ldap.INVALID_SYNTAX: {'info': 'gidNumber: value #0 invalid per syntax', 'desc': 'Invalid syntax'}
```
I changed lines 84-5 of the obol script to:
```
        if gidNumber == 'False':
            raise Exception('The group %s does not exist' % group)
```
and got:
```
[root@controller1 controller]# obol user add --password 123 --group superusers jerobeam
gidNumber = False
Traceback (most recent call last):
  File "/usr/local/bin/obol", line 561, in <module>
    cmd(**args)
  File "/usr/local/bin/obol", line 86, in user_add
    raise Exception('The group %s does not exist' % group)
Exception: The group superusers does not exist
```
, which makes more sense.

- Weird things happen with gid numbers. When I assign a new user to the pre-existing users group, it gets listed as member of that group, but it gets gidNumber 100 instead of 151. I noticed this only with the users group:
```
[root@controller1 controller]# obol user add --password 123 --group users jennifer
[root@controller1 controller]# obol group show users
{
    "cn": "users", 
    "gidNumber": "151", 
    "member": [
        "uid=jerobeam,ou=People,dc=local", 
        "uid=joram,ou=People,dc=local", 
        "uid=jennifer,ou=People,dc=local"
    ]
}
[root@controller1 controller]# obol user show jennifer
{
    "cn": "jennifer", 
    "gidNumber": "100", 
    "homeDirectory": "/trinity/home/jennifer", 
    "loginShell": "/bin/bash", 
    "shadowExpire": "-1", 
    "shadowLastChange": "17284", 
    "shadowMax": "99999", 
    "shadowMin": "0", 
    "shadowWarning": "7", 
    "sn": "jennifer", 
    "uid": "jennifer", 
    "uidNumber": "1081", 
    "userPassword": "{SSHA}cmEN5rCfbkJLtFFCbfSlrHBJuM4SBGHM"
}
```

**Comment by hicham-a** [comment]
Thanks Marc for the tests.
- I have submitted patchs for the first two points.
- The issue with the 'users' group stems from the fact that it is duplicate (GIDs 100 and 150). I have deleted it since it is not used at the moment.
